version: '2'
services:
  customshopping-app:
    image: customshopping
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://customshopping-mssql:1433;database=customShopping
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://customshopping-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://customshopping-elasticsearch:9200
    ports:
      - 8080:8080
  customshopping-mssql:
    extends:
      file: mssql.yml
      service: customshopping-mssql
  customshopping-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: customshopping-elasticsearch
